from django.urls import path
from admin_panel import views
urlpatterns = [
    path('', views.admin_signup, name = 'admin_signup'),
    path('', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name = 'dashboard_view'),
    path('branch_view/', views.branch_view, name = 'branch_view'),
    path('add_branch/', views.add_branch, name = 'add_branch'),
    path('delete_branch/<int:branch_id>/', views.delete_branch, name = 'delete_branch'),
    path('update_branch/<int:branch_id>/', views.update_branch, name = 'update_branch'),
    path('subject_view/', views.subject_view, name = 'subject_view'),
    path('add_subject/', views.add_subject, name = 'add_subject'),
    path('delete_subject/<int:subject_id>/', views.delete_subject, name = 'delete_subject'),
    path('update_subject/<int:subject_id>/', views.update_subject, name = 'update_subject'),
    path('teacher/', views.teacher_view, name = 'teacher'),
    path('add_teacher/', views.add_teacher, name = 'add_teacher'),
    path('delete_teacher/<str:email>/', views.delete_teacher, name = 'delete_teacher'),
    path('update_teacher/<str:email>/', views.update_teacher, name = 'update_teacher'),
    path('student/', views.student_view, name = 'student'),
    path('add_student/', views.add_student, name = 'add_student'),
    path('delete_student/<str:email>/', views.delete_student, name = 'delete_student'),
    path('update_student/<str:email>/', views.update_student, name = 'update_student'),
    path('teacher_dashboard/', views.teacher_dashboard, name = 'teacher_dashboard'),
    path('students_under_teacher/', views.students_under_teacher, name = 'students_under_teacher'),
    path('student_attendance/', views.student_attendance, name = 'student_attendance'),
    path('add_result/', views.add_result, name = 'add_result'),
    path('student_results_list/', views.student_results_list, name = 'student_results_list'),
    path('student_dashboard/<int:student_id>/', views.student_dashboard, name = 'student_dashboard'),
    path('student_attendance_view/<int:student_id>/', views.student_attendance_view, name = 'student_attendance_view'),
    path('student_result_view/<int:student_id>/', views.student_result_view, name = 'student_result_view'),
    path('student_profile_view/<int:student_id>/', views.student_profile_view, name = 'student_profile_view'),
]
