# Generated by Django 5.1.1 on 2025-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_model',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
