# Generated by Django 5.1.1 on 2025-01-31 08:24

import admin_panel.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_teacher_assigned_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', admin_panel.models.CustomUserManager()),
            ],
        ),
    ]
