# Generated by Django 5.1.1 on 2025-02-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_teacher_assigned_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
