# Generated by Django 5.1.1 on 2025-02-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_branches_remove_subject_course_alter_students_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_record', to='admin_panel.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_record', to='admin_panel.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_record', to='admin_panel.teacher')),
            ],
        ),
    ]
