# Generated by Django 5.1.1 on 2025-02-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_enrolled_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='enrolled_subject',
            field=models.ManyToManyField(related_name='students', to='admin_panel.subject'),
        ),
        migrations.DeleteModel(
            name='Enrolled_subject',
        ),
    ]
