# Generated by Django 5.1.1 on 2025-02-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
