# Generated by Django 5.1.1 on 2025-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_studentresult_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
